// react-source/react-app/src/pages/Home.js
import React from "react";
import Body from '../commons/Body';
import './Home.css';
import { FaSearchLocation } from "react-icons/fa";
import { AiOutlineCloudServer } from "react-icons/ai";

function Home(){
    return (
    <Body children={
      <div id="id-card" className="card">
  <div className="card-body">
        <div className="container">
          <div className="row">
            <div className="col-md-4">
            <img src="https://res.cloudinary.com/dfptza4sj/image/upload/v1633241218/Portfolio/Me_hfwalc.png" className="card-img-top" alt="Varun Setia"/>
            <h5 className="card-title">Varun Setia</h5>
            </div>
            <div className="col-md-8">
            <p className="card-text">Hey, this is my introduction!</p>
            <p className="location"><FaSearchLocation/> Delhi</p>
            <p> I am a full stack developer, my main area of focus is<span className="big-icon"> <AiOutlineCloudServer/> </span>cloud oriented development. </p>
            <p>6X Certified in Azure Cloud!</p>
            <p>I am system designing enthusiast.</p>
            <p><span className="exper">4+ Years </span></p>
              
            </div>
          </div>
        </div>
  </div>
  <div className="card-body">
        <div className="container">
          <div className="row">
            <div className="col-md-12">
        <p>I have worked across many verticals of technology. I have developed enterprise applications by following proper design and architecture guidelines. I had focused mainly on developing scalable microservices solution. The solutions built are majorly deployed on cloud infrastructure.</p>
        <p> I had worked on front-end technologies namely Angular, React and jQuery. This website has been built on ReactJs by me.</p>
        <p>In backend technologies, i had worked on .NET Core and Node JS.</p>
        <p>The database technologies includes SQL and No-SQL namely SQL Server, MySQL, MongoDB and RedisDB.  </p>
        <p>The cloud platforms that i had explored are Azure and AWS. My main expertise is in Azure Cloud.</p>
        <p>Also, for microservices i had worked on Docker platform and very basic in Kubernetes.</p>
            </div>
          </div>
        </div>
  </div>
</div>
    }>
  </Body>);
}

export default Home;

// ng-source/src/app/pages/home/home.component.ts
import { AfterViewInit, Component, OnInit } from '@angular/core';
import { LoaderService } from 'src/app/commons/services/loader/loader.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit,AfterViewInit {

  constructor(private loader:LoaderService) { }

  ngOnInit(): void {
  }

  ngAfterViewInit(): void{
    this.loader.SHOW_LOADER = false;
  }

}

<div id="introduction-wrapper">
  <div id="my-profile-details-card">
<app-profile-card
profileUrl = "https://res.cloudinary.com/dfptza4sj/image/upload/v1633241218/Portfolio/Me_hfwalc.png"
fullName = "Varun Setia"
introduction = "Hey, I am Varun Setia. I am born and I live in Delhi. I am a full Stack Developer, my main area of focus is cloud oriented development. I am System Designing Enthusiast.
I have total Experience of more than 4 Years. I love North Indian food. I am always ready to disuss new ideas."
moreCsv ="Microservices Development,6 Certifications - 5 Azure and 1 Microsoft Power Platform,Single Pager Application Development using Angular, Express with Node JS and .NET Core Web APIs"
visitLinkName="Read More"
visitLink="/skillset"
></app-profile-card>
</div>
</div>
